EnrollementApplication/EnrollementApplication/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace EnrollementApplication.Models
{
    //[Bind(Exclude = "EnrollmentId")]
    public class Enrollment
    {
        public virtual int EnrollmentId { get; set; }


        public virtual int StudentId { get; set; }
        public virtual int CourseId { get; set; }

        [Required(ErrorMessage ="You must enter a gade.")]
        [RegularExpression("[A-F]", ErrorMessage ="Grade must be either A, B, C, D, E, or F.")]
        public virtual string Grade { get; set; }

        public virtual Student Student { get; set; }
        public virtual Course Course { get; set;}
        public virtual bool IsActive { get; set; }

        [Display(Name ="Assigned Campus")]
        [Required(ErrorMessage ="You must enter an assigned campus.")]
        public virtual string AssignedCampus { get; set; }

        [Display(Name = "Enrolled in Semester")]
        [Required(ErrorMessage ="You must select an enrollment semester.")]
        public virtual string EnrollmentSemester { get; set; }

        [Display(Name = "Enrollment Year")]
        [Required(ErrorMessage ="Enrollment year required.")]
        [Range(2018, int.MaxValue, ErrorMessage ="Year of enrollment must be 2018 or later.")]
        public virtual int EnrollmentYear { get; set; }

        [InvalidChars("@#^*", ErrorMessage = "Invalid characters found")]
        public virtual string Notes { get; set; }

    }
}

EnrollementApplication/EnrollementApplication/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnrollementApplication.Models;

namespace EnrollementApplication.Controllers
{
    public class EnrollmentController : Controller
    {
        private EnrollementDB db = new EnrollementDB();

        // GET: Enrollment
        public ActionResult Index()
        {
            var enrollments = db.Enrollments.Include(e => e.Course).Include(e => e.Student);
            return View(enrollments.ToList());
        }

        // partial view search by Student
        public ActionResult StudentSearch(string q)
        {
            var student = GetStudent(q);
            return PartialView(student);
        }
        private List<Student> GetStudent(string searchstring)
        {
            return db.Students.Where(a => a.LastName.Contains(searchstring) || a.FirstName.Contains(searchstring)).ToList();

        }

        // partial view search by Course
        public ActionResult CourseSearch(string q)
        {
            var course = GetCourse(q);
            return PartialView(course);
        }
        private List<Course> GetCourse(string searchstring)
        {
            return db.Courses.Where(a => a.Title.Contains(searchstring)).ToList();

        }

        // GET: Enrollment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollment/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title");
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "LastName");
            return View();
        }

        // POST: Enrollment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EnrollmentId,StudentId,CourseId,Grade,IsActive,AssignedCampus,EnrollmentSemester,EnrollmentYear,Notes")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Add(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "LastName", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "LastName", enrollment.StudentId);
            return View(enrollment);
        }

        // POST: Enrollment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EnrollmentId,StudentId,CourseId,Grade,IsActive,AssignedCampus,EnrollmentSemester,EnrollmentYear,Notes")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "LastName", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = db.Enrollments.Find(id);
            db.Enrollments.Remove(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnrollementApplication/EnrollementApplication/Views/Enrollment/CourseSearch.cshtml
@model IEnumerable<EnrollementApplication.Models.Course>
<div id="searchresultscourse">
    <ul>
        @foreach (var item in Model)
        {
            <li>@item.Title</li>
        }
    </ul>
</div> 

EnrollementApplication/EnrollementApplication/Views/Enrollment/Create.cshtml
@model EnrollementApplication.Models.Enrollment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Enrollment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Grade, "Grade", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Grade, null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "Is Active", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.IsActive, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "Assigned Campus", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AssignedCampus, null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AssignedCampus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "Enrolled in Semester", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div>
                @Html.LabelFor(model => model.EnrollmentSemester, "Spring")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "Spring", htmlAttributes: new { @class = "form-control" })
            </div>
            <div>
                @Html.LabelFor(model => model.EnrollmentSemester, "Summer")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "Summer", htmlAttributes: new { @class = "form-control" })
            </div>
            <div>
                @Html.LabelFor(model => model.EnrollmentSemester, "Fall")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "Fall", htmlAttributes: new { @class = "form-control" })
            </div>
            @Html.ValidationMessageFor(model => model.EnrollmentSemester, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "Enrollment Year", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EnrollmentYear, null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EnrollmentYear, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Notes, "Notes", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Notes, null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnrollementApplication/EnrollementApplication/Views/Enrollment/Delete.cshtml
@model EnrollementApplication.Models.Enrollment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EnrollementApplication/EnrollementApplication/Views/Enrollment/Details.cshtml
@model EnrollementApplication.Models.Enrollment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.CheckBoxFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignedCampus)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.AssignedCampus, new { @class = "form-control", @readonly = "true" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentSemester)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentSemester)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentYear)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.EnrollmentYear, new { @class = "form-control", @readonly = "true" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.Notes, new { @class = "form-control", @readonly = "true" })
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EnrollmentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EnrollementApplication/EnrollementApplication/Views/Enrollment/Edit.cshtml
@model EnrollementApplication.Models.Enrollment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Enrollment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EnrollmentId)

    <div class="form-group">
        @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Grade, "Grade", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Grade, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, "IsActive", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.IsActive, false)
            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AssignedCampus, "AssignedCampus", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AssignedCampus, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AssignedCampus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentSemester, "EnrollmentSemester", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div>
                @Html.LabelFor(model => model.EnrollmentSemester, "Spring")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "Spring", htmlAttributes: new { @class = "form-control" })
            </div>
            <div>
                @Html.LabelFor(model => model.EnrollmentSemester, "Summer")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "Summer", htmlAttributes: new { @class = "form-control" })
            </div>
            <div>
                @Html.LabelFor(model => model.EnrollmentSemester, "Fall")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "Fall", htmlAttributes: new { @class = "form-control" })
            </div>
            @Html.ValidationMessageFor(model => model.EnrollmentSemester, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentYear, "EnrollmentYear", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EnrollmentYear, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EnrollmentYear, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Notes, "Notes", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Notes, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnrollementApplication/EnrollementApplication/Views/Enrollment/Index.cshtml
@model IEnumerable<EnrollementApplication.Models.Enrollment>

@{
    ViewBag.Title = "Index";
}
<br /><br />
<h2>Index</h2>

<div class="panel panel-default">
    <div class="panel-body">
        <b>Search for Student by name.</b>
        @using (Ajax.BeginForm("StudentSearch", "Enrollment",
            new AjaxOptions
            {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                UpdateTargetId = "searchresultsstudent",
                LoadingElementId = "ajax-loader",
                OnFailure = "searchFailed"
            }
            )
        )
        {
            <input type="text" name="q" />
            <input type="submit" value="search" />
            <img id="ajax-loader" src="@Url.Content("~/Images/ajax-loader.gif")" style="display:none" />
        }
        <div id="searchresultsstudent">
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        <b>Search for Course by title.</b>
        @using (Ajax.BeginForm("CourseSearch", "Enrollment",
            new AjaxOptions
            {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                UpdateTargetId = "searchresultscourse",
                LoadingElementId = "ajax-loader",
                OnFailure = "searchFailed"
            }
            )
        )
        {
            <input type="text" name="q" />
            <input type="submit" value="search" />
            <img id="ajax-loader" src="@Url.Content("~/Images/ajax-loader.gif")" style="display:none" />
        }
        <div id="searchresultscourse">
        </div>
    </div>
</div>


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedCampus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnrollmentSemester)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnrollmentYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.CheckBoxFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedCampus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentSemester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.EnrollmentId }) |
                @Html.ActionLink("Details", "Details", new { id = item.EnrollmentId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.EnrollmentId })
            </td>
        </tr>
    }

</table>

@section Scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/Apps/EnrollmentScript.js"></script>
}

EnrollementApplication/EnrollementApplication/Views/Enrollment/StudentSearch.cshtml
@model IEnumerable<EnrollementApplication.Models.Student>
<div id="searchresultsstudent">
    <ul>
        @foreach (var item in Model)
        {
            <li>@item.FirstName @item.LastName</li>
        }
    </ul>
</div> 